// TypeScript Version: 3.3 
/// <reference path="ts-dom.d.ts" /> 
// Mini App typings
/// <reference path="./app.d.ts" /> 
/// <reference path="./component.d.ts" />
/// <reference path="./page.d.ts" />
/// <reference path="./api/index.d.ts" />
/// <reference path="./global.d.ts" />
/// <reference path="./event.d.ts" />
